//
//  AWSMobileHubContentManager.h
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//

#import <UIKit/UIKit.h>

//! Project version number for AWSMobileContentManager.
FOUNDATION_EXPORT double AWSMobileHubContentManagerVersionNumber;

//! Project version string for AWSMobileContentManager.
FOUNDATION_EXPORT const unsigned char AWSMobileHubContentManagerVersionString[];

#import <AWSMobileHubContentManager/AWSContentManager.h>
#import <AWSMobileHubContentManager/AWSUserFileManager.h>
